# Generated by Django 6.0.7 on 2026-07-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColaboradorCadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_empresa', models.CharField(help_text='Matricula. Apenas numeros (RG-RESP-002).', max_length=10, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('ativo', models.BooleanField(default=True, help_text='Inativo = nao aparece na pesquisa (RG-RESP-003).')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Cadastro de Colaboradores',
                'db_table': 'colaboradores_cadastro',
                'ordering': ['nome'],
            },
        ),
    ]
