-- ============================================================
-- SEED: cat_locais
-- Sistema RAD — Locais disponíveis (CAT-002)
-- Total: 70 locais
-- Categorias: estacao, patio, cabine, subestacao, terminal, vse, almox
-- Nota: Terminais usam siglas prefixadas TM para evitar conflito
--       com siglas de estações de mesmo código (DBO, JBO, GUA)
-- ============================================================
TRUNCATE TABLE cat_locais RESTART IDENTITY CASCADE;

INSERT INTO cat_locais (sigla, nome, categoria) VALUES
  ('BFU', 'Barra Funda', 'estacao'),
  ('LUZ', 'Luz', 'estacao'),
  ('BAS', 'Brás', 'estacao'),
  ('CCO', 'CCO Brás', 'estacao'),
  ('TAT', 'Tatuapé', 'estacao'),
  ('ITQ', 'Itaquera', 'estacao'),
  ('DBO', 'Dom Bosco', 'estacao'),
  ('JBO', 'José Bonifácio', 'estacao'),
  ('GUA', 'Guaianazes', 'estacao'),
  ('AGN', 'Antônio Gianetti Neto', 'estacao'),
  ('FVC', 'Ferraz de Vasconcelos', 'estacao'),
  ('POÁ', 'Poá', 'estacao'),
  ('CVN', 'Calmon Viana', 'estacao'),
  ('SUZ', 'Suzano', 'estacao'),
  ('JPB', 'Jundiapeba', 'estacao'),
  ('BCB', 'Braz Cubas', 'estacao'),
  ('MDC', 'Mogi das Cruzes', 'estacao'),
  ('EST', 'Estudantes', 'estacao'),
  ('USL', 'Usp Leste', 'estacao'),
  ('ERM', 'Comendador Ermelino', 'estacao'),
  ('SMP', 'São Miguel Paulista', 'estacao'),
  ('JHE', 'Jardim Helena', 'estacao'),
  ('ITI', 'Itaim Paulista', 'estacao'),
  ('JRO', 'Jardim Romano', 'estacao'),
  ('EMF', 'Eng. Manoel Feio', 'estacao'),
  ('IQC', 'Itaquaquecetuba', 'estacao'),
  ('ARC', 'Aracaré', 'estacao'),
  ('EGO', 'Eng. Goulart', 'estacao'),
  ('GCE', 'Guarulhos CECAP', 'estacao'),
  ('AGU', 'Aeroporto Guarulhos', 'estacao'),
  ('PAT 001', 'Patio Luz', 'patio'),
  ('PAT 003', 'Patio Eng São Paulo', 'patio'),
  ('PAT 005', 'Patio para Lastros e Dormentes', 'patio'),
  ('PAT 006', 'Vias de Estacionamento Guaianazes', 'patio'),
  ('PAT 007', 'Estaleiro TLS', 'patio'),
  ('PAT 008', 'Lavador de Trem', 'patio'),
  ('PAT 009', 'Patio Mogi das Cruzes', 'patio'),
  ('PAT 011', 'Base de Manutenção - Metalurgia e AMVs', 'patio'),
  ('PAT 013', 'Patio Eng Manoel Feio', 'patio'),
  ('PAT 014', 'Patio Calmon Viana', 'patio'),
  ('CSFVA', 'Ferraz de Vasconcelos', 'cabine'),
  ('CSGUA', 'Guaianazes', 'cabine'),
  ('CSALV', 'Arthur Alvim', 'cabine'),
  ('CSVTD', 'Carlos de Campos - Vila Matilde', 'cabine'),
  ('CSJBO', 'José Bonifácio', 'cabine'),
  ('CSJPB', 'Jundiapeba', 'cabine'),
  ('CSEST', 'Estudantes', 'cabine'),
  ('CSITQ', 'Itaquaquecetuba', 'cabine'),
  ('CSITI', 'Itaim Paulista', 'cabine'),
  ('CSBAS', 'Brás', 'cabine'),
  ('CSEGO', 'Eng. Goulart', 'cabine'),
  ('CSCEC', 'Guarulhos CECAP', 'cabine'),
  ('SEDBO', 'Dom Bosco', 'subestacao'),
  ('SEPTR', 'Patriarca', 'subestacao'),
  ('SECVN', 'Calmon Viana', 'subestacao'),
  ('SEBCB', 'Braz Cubas', 'subestacao'),
  ('SEMAL', 'Memorial da America Latina', 'subestacao'),
  ('SEGUA', 'Guaianazes', 'subestacao'),
  ('SEEMF', 'Manoel Feio', 'subestacao'),
  ('SESGU', 'Sebastiao Gualberto (Patio)', 'subestacao'),
  ('SEERM', 'C. Ermelino Matarazzo', 'subestacao'),
  ('SEEGO', 'Eng. Goulart', 'subestacao'),
  ('SEISP', 'Eng. São Paulo', 'subestacao'),
  ('SEAGU', 'Aeroporto', 'subestacao'),
  ('SEAYS', 'Ayrton Senna', 'subestacao'),
  ('TMDBO', 'Estação Dom Bosco', 'terminal'),
  ('TMJBO', 'Estação José Bonifácio', 'terminal'),
  ('TMGUA', 'Estação Guaianazes', 'terminal'),
  ('VSE', 'R. Alayde de Souza Costa, 234 - Itaquera', 'vse'),
  ('ALMOX', 'Av. Francisco Rodrigues Filho, 121 - Vila Mogilar', 'almox');

-- Total: 70 registros
