# Generated by Django 6.0.7 on 2026-07-17 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(help_text='Identificador tecnico do campo (ex.: responsavel_atividade).', max_length=100, unique=True)),
                ('rotulo', models.CharField(help_text='Nome exibido ao usuario (ex.: "Responsável Atividade").', max_length=200)),
                ('habilitado', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Campo do Formulário',
                'verbose_name_plural': 'Configuração de Campos do Formulário',
                'db_table': 'campos_formulario',
                'ordering': ['rotulo'],
            },
        ),
    ]
