# Generated by Django 6.0.7 on 2026-07-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatAcaoAmv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Acao AMV',
                'verbose_name_plural': 'Catalogo: Acoes AMV',
                'db_table': 'cat_acoes_amv',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CatLinha',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Linha',
                'verbose_name_plural': 'Catalogo: Linhas',
                'db_table': 'cat_linhas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CatLocal',
            fields=[
                ('sigla', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('estacao', 'Estacao'), ('patio', 'Patio'), ('cabine', 'Cabine'), ('subestacao', 'Subestacao'), ('terminal', 'Terminal'), ('vse', 'VSE'), ('almox', 'Almoxarifado')], max_length=50)),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Catalogo: Locais',
                'db_table': 'cat_locais',
                'ordering': ['sigla'],
            },
        ),
        migrations.CreateModel(
            name='CatMch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(max_length=50, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('via', models.CharField(blank=True, help_text='MCH29U-BFU esta pendente de preenchimento (DT-PEND / EXP-PEND-001).', max_length=20)),
                ('ur', models.CharField(max_length=50)),
                ('local_amv', models.CharField(max_length=100)),
                ('linha', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'MCH',
                'verbose_name_plural': 'Catalogo: MCHs',
                'db_table': 'cat_mch',
                'ordering': ['identificacao'],
            },
        ),
        migrations.CreateModel(
            name='CatMotivoAtraso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('requer_descricao', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Motivo de Atraso',
                'verbose_name_plural': 'Catalogo: Motivos de Atraso',
                'db_table': 'cat_motivos_atraso',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CatServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, help_text='Texto exibido no botao de ajuda (?).', null=True)),
                ('requer_amv', models.BooleanField(default=False, help_text='TRUE somente para Manutencao em AMV.')),
                ('requer_descricao', models.BooleanField(default=False, help_text='TRUE somente para Outros.')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Servico',
                'verbose_name_plural': 'Catalogo: Servicos',
                'db_table': 'cat_servicos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CatTipoDefeitoAmv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Defeito AMV',
                'verbose_name_plural': 'Catalogo: Tipos de Defeito AMV',
                'db_table': 'cat_tipos_defeito_amv',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CatTipoManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Manutencao',
                'verbose_name_plural': 'Catalogo: Tipos de Manutencao',
                'db_table': 'cat_tipos_manutencao',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CatVia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Via',
                'verbose_name_plural': 'Catalogo: Vias',
                'db_table': 'cat_vias',
                'ordering': ['nome'],
            },
        ),
    ]
