# Generated by Django 6.0.7 on 2026-07-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatEquipe',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Catalogo: Equipes',
                'db_table': 'cat_equipes',
                'ordering': ['codigo'],
            },
        ),
    ]
