# Generated by Django 6.0.7 on 2026-07-15 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(help_text='Login unico. Usado para autenticacao sem senha (RG-AUTH-001).', max_length=100, unique=True)),
                ('ativo', models.BooleanField(default=True, help_text='Inativo = nao consegue fazer login.')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500, unique=True)),
                ('validade', models.DateTimeField(help_text='data_criacao + VALIDADE_TOKEN_DIAS (padrao 7 dias).')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.CharField(blank=True, help_text='Identificacao do dispositivo. Apenas informativo.', max_length=255, null=True)),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
                'db_table': 'tokens',
                'indexes': [models.Index(fields=['token'], name='idx_tokens_token'), models.Index(fields=['usuario'], name='idx_tokens_id_usuario'), models.Index(fields=['validade'], name='idx_tokens_validade')],
            },
        ),
        migrations.CreateModel(
            name='UsuarioPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.CharField(choices=[('usuario', 'Usuario'), ('supervisor', 'Supervisor'), ('administrador', 'Administrador')], max_length=20)),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='perfis', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfis de Usuario',
                'db_table': 'usuario_perfis',
                'constraints': [models.UniqueConstraint(fields=('usuario', 'perfil'), name='uniq_usuario_perfil')],
            },
        ),
    ]
