# Generated by Django 6.0.7 on 2026-08-27 18:06
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_log_senha_temporaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsenhatemporaria',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
