"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carrega variaveis sensiveis do .env — nunca no codigo-fonte
# (PADROES_E_DIRETRIZES secao 6 - Seguranca)
load_dotenv(BASE_DIR / '.env')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-defina-no-env')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Producao: forca HTTPS e cookies seguros quando DEBUG=False. Nao afeta
# desenvolvimento local (DEBUG=True), entao nao muda nada do fluxo
# existente -- so passa a valer quando alguem configurar DEBUG=False
# no .env de producao (ver checklist no README).
if not DEBUG:
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'True') == 'True'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', 60 * 60 * 24 * 30))  # 30 dias
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # Necessario atras de um proxy reverso (Railway/Render/nginx) que
    # termina o TLS antes do Django -- sem isso o Django nunca veria a
    # requisicao como HTTPS e o redirect acima entraria em loop.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Apps do Sistema RAD (PADROES_E_DIRETRIZES secao 4.3)
    'usuarios',
    'rad',
    'catalogos',
    'consulta',
    'colaboradores',
    'configuracoes',
    'interface',
]

# Constantes do sistema (PADROES_E_DIRETRIZES secao 4.1 - UPPER_SNAKE_CASE)
VALIDADE_TOKEN_DIAS = int(os.getenv('VALIDADE_TOKEN_DIAS', 7))
LOGS_ATIVOS = os.getenv('LOGS_ATIVOS', 'False') == 'True'

# Armazenamento de anexos (RG-ANX-007/008): o banco guarda so a
# referencia (caminho) ao arquivo, nao o arquivo em si. Em desenvolvimento
# local os arquivos ficam no filesystem local; em producao a Fase 2
# (DT-PEND) definira o servidor de arquivos/object storage definitivo.
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

# RG-ANX-003/004/005: 2 fotos por categoria (Intervenção verificada /
# Ação realizada), 1 PDF, 10MB por arquivo.
LIMITE_FOTOS_POR_CATEGORIA = 2
LIMITE_PDF_POR_RAD = 1
LIMITE_TAMANHO_ARQUIVO_BYTES = 10 * 1024 * 1024  # 10MB

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
if not DEBUG:
    # Em desenvolvimento o runserver ja serve estatico nativamente;
    # WhiteNoise so entra em producao (gunicorn nao serve estatico
    # sozinho). Logo depois do SecurityMiddleware, como a doc do
    # WhiteNoise recomenda.
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# DATABASE_URL tem prioridade quando definida -- e o padrao usado por
# Railway, Render, Heroku e a maioria dos PaaS modernos (uma unica
# variavel em vez de host/porta/usuario/senha separados). Se nao
# estiver definida, cai de volta nas variaveis DB_* de sempre -- assim
# o desenvolvimento local continua identico, e a escolha do provedor de
# nuvem (ainda pendente) nao exige mudar este arquivo.
if os.getenv('DATABASE_URL'):
    import dj_database_url

    DATABASES = {
        'default': dj_database_url.config(
            env='DATABASE_URL', conn_max_age=600, ssl_require=not DEBUG
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.postgresql'),
            'NAME': os.getenv('DB_NAME', 'sistema_rad'),
            'USER': os.getenv('DB_USER', 'rad_dev'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise com hash+compressao so em producao -- em desenvolvimento
# (DEBUG=True) exigiria rodar collectstatic a cada mudanca de CSS/JS
# para o runserver enxergar o arquivo, o que atrapalha o ciclo normal
# de desenvolvimento. runserver ja serve estatico direto sem isso.
if not DEBUG:
    STORAGES = {
        'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
        'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'},
    }
