"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carrega variaveis sensiveis do .env — nunca no codigo-fonte
# (PADROES_E_DIRETRIZES secao 6 - Seguranca)
load_dotenv(BASE_DIR / '.env')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-defina-no-env')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# CORS: libera o domínio do Hub (Ferramenta de Atalhos) a chamar a API
# do RAD (login, validação de token) direto do navegador. Sem isso, o
# navegador bloqueia a chamada por vir de um domínio diferente.
# Documento de continuidade do Hub, decisão 1 (CORS).
CORS_ALLOWED_ORIGINS = os.getenv(
    'CORS_ALLOWED_ORIGINS', 'https://hub-atalhos.onrender.com'
).split(',')

# Producao: forca HTTPS e cookies seguros quando DEBUG=False. Nao afeta
# desenvolvimento local (DEBUG=True), entao nao muda nada do fluxo
# existente -- so passa a valer quando alguem configurar DEBUG=False
# no .env de producao (ver checklist no README).
if not DEBUG:
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'True') == 'True'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', 60 * 60 * 24 * 30))  # 30 dias
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # Necessario atras de um proxy reverso (Railway/Render/nginx) que
    # termina o TLS antes do Django -- sem isso o Django nunca veria a
    # requisicao como HTTPS e o redirect acima entraria em loop.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages',
    'corsheaders',
    # Apps do Sistema RAD (PADROES_E_DIRETRIZES secao 4.3)
    'usuarios',
    'rad',
    'catalogos',
    'consulta',
    'colaboradores',
    'configuracoes',
    'dashboard',
    'interface',
]

# Constantes do sistema (PADROES_E_DIRETRIZES secao 4.1 - UPPER_SNAKE_CASE)
VALIDADE_TOKEN_DIAS = int(os.getenv('VALIDADE_TOKEN_DIAS', 7))
LOGS_ATIVOS = os.getenv('LOGS_ATIVOS', 'False') == 'True'

# 30/07/2026: rate limit de login -- protege contra tentativa de forca
# bruta agora que o login exige senha (ver usuarios/views.py::login e
# CLAUDE.md, achado de seguranca corrigido). Apos MAXIMO_TENTATIVAS_LOGIN
# erros seguidos, a conta fica bloqueada por BLOQUEIO_LOGIN_MINUTOS --
# contador zera a cada login correto.
MAXIMO_TENTATIVAS_LOGIN = int(os.getenv('MAXIMO_TENTATIVAS_LOGIN', 5))
BLOQUEIO_LOGIN_MINUTOS = int(os.getenv('BLOQUEIO_LOGIN_MINUTOS', 15))

# 30/07/2026 (Seguranca A02 -- OWASP Top 10:2025): endereço do /admin/
# do Django movido pra um caminho nao obvio -- reduz drasticamente o
# volume de bots que tentam login as cegas em "/admin/", o alvo mais
# escaneado da internet. Trocar esse valor por env var em produção
# (ADMIN_URL_PATH) se quiser um caminho so seu, sem depender de deploy
# de codigo -- so avisar quem precisa saber o endereço novo. Mesmo
# esquema de bloqueio por tentativas do login normal, mas por IP (ver
# usuarios/middleware.py e usuarios/signals.py).
ADMIN_URL_PATH = os.getenv('ADMIN_URL_PATH', 'gestao-sistema-8f3k2x')
MAXIMO_TENTATIVAS_ADMIN = int(os.getenv('MAXIMO_TENTATIVAS_ADMIN', 5))
BLOQUEIO_ADMIN_MINUTOS = int(os.getenv('BLOQUEIO_ADMIN_MINUTOS', 15))

# 30/07/2026: URL publica do site, usada pra montar o link do e-mail de
# redefinicao de senha (usuarios/servicos_email.py). Sem barra no final.
URL_BASE_SITE = os.getenv('URL_BASE_SITE', 'https://raddigital.onrender.com')

# 25/08/2026 (achado de auditoria de seguranca): rate limit no
# "Esqueci minha senha" -- sem isso, alguem podia repetir o POST pro
# mesmo e-mail indefinidamente, nao pra descobrir senha nenhuma (o
# link so prova identidade, nunca revela a senha), mas pra spamar a
# caixa de entrada da pessoa. Limite por conta (nao por IP): o que
# importa aqui e proteger o DESTINATARIO do e-mail, nao identificar o
# solicitante -- um atacante pode trocar de IP a vontade, mas o
# e-mail-alvo continua sendo o mesmo. Ver usuarios/views.py::
# solicitar_redefinicao_senha.
MAXIMO_SOLICITACOES_REDEFINICAO_SENHA = int(os.getenv('MAXIMO_SOLICITACOES_REDEFINICAO_SENHA', 3))
JANELA_REDEFINICAO_SENHA_MINUTOS = int(os.getenv('JANELA_REDEFINICAO_SENHA_MINUTOS', 60))

# 30/07/2026: envio de e-mail (redefinicao de senha). Sem as variaveis
# EMAIL_* no .env, cai no backend "console" -- imprime o e-mail no log
# em vez de enviar de verdade. Isso vale MESMO EM PRODUCAO ate Andre
# configurar uma conta SMTP real (Gmail com senha de app, ou um servico
# tipo Resend/SendGrid). Variaveis esperadas:
#   EMAIL_HOST, EMAIL_PORT, EMAIL_HOST_USER, EMAIL_HOST_PASSWORD,
#   EMAIL_USE_TLS (True/False), DEFAULT_FROM_EMAIL
EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND',
    'django.core.mail.backends.smtp.EmailBackend'
    if os.getenv('EMAIL_HOST')
    else 'django.core.mail.backends.console.EmailBackend',
)
EMAIL_HOST = os.getenv('EMAIL_HOST', '')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').strip().lower() == 'true'
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'nao-responda@raddigital.onrender.com')

# Armazenamento de anexos (RG-ANX-007/008): o banco guarda so a
# referencia (caminho) ao arquivo, nao o arquivo em si.
#
# 22/07/2026: o disco local do Render (plano free) e efemero -- toda
# foto enviada e apagada a cada deploy/restart/"sono" do servico,
# mesmo que o registro no banco continue existindo (RadAnexo aponta
# pra um arquivo que sumiu). Por isso, quando as variaveis R2_* abaixo
# estao definidas, o storage de anexos passa a ser o Cloudflare R2
# (compativel com a API do S3) -- um servico de arquivos que nao
# depende do disco do servidor, entao sobrevive a qualquer deploy.
#
# Sem essas variaveis definidas (ex.: rodando local), cai de volta pro
# disco local de sempre -- nada muda no dia a dia de desenvolvimento.
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

AWS_ACCESS_KEY_ID = os.getenv('R2_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('R2_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.getenv('R2_BUCKET_NAME')
AWS_S3_ENDPOINT_URL = os.getenv('R2_ENDPOINT_URL')  # ex: https://<account_id>.r2.cloudflarestorage.com
AWS_S3_CUSTOM_DOMAIN = os.getenv('R2_PUBLIC_DOMAIN')  # opcional, se configurar dominio publico no bucket
AWS_DEFAULT_ACL = None  # R2 nao usa ACL do jeito que o S3 usa -- evita erro na hora do upload
AWS_S3_FILE_OVERWRITE = False  # dois anexos com o mesmo nome de arquivo nao se sobrescrevem
AWS_QUERYSTRING_AUTH = True  # URLs assinadas com validade -- os anexos nao sao publicos

USANDO_ARMAZENAMENTO_EM_NUVEM = bool(
    AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY and AWS_STORAGE_BUCKET_NAME and AWS_S3_ENDPOINT_URL
)

# RG-ANX-003/004/005: 2 fotos por categoria (Intervenção verificada /
# Ação realizada), 1 PDF, 10MB por arquivo.
LIMITE_FOTOS_POR_CATEGORIA = 2
LIMITE_PDF_POR_RAD = 1
LIMITE_TAMANHO_ARQUIVO_BYTES = 10 * 1024 * 1024  # 10MB

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # CORS: precisa ficar o mais alto possível na lista, antes de
    # qualquer middleware que possa gerar uma resposta (ex:
    # CommonMiddleware) -- exigência da própria documentação do
    # django-cors-headers.
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 30/07/2026 (Seguranca A02): bloqueio do /admin/ por tentativas
    # erradas, por IP. Precisa vir DEPOIS do AuthenticationMiddleware
    # (usa request.META, nao depende de auth, mas mantem a ordem
    # convencional de "seguranca por cima, funcionalidade por baixo").
    'usuarios.middleware.BloqueioAdminMiddleware',
]
if not DEBUG:
    # Em desenvolvimento o runserver ja serve estatico nativamente;
    # WhiteNoise so entra em producao (gunicorn nao serve estatico
    # sozinho). Logo depois do SecurityMiddleware, como a doc do
    # WhiteNoise recomenda.
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# DATABASE_URL tem prioridade quando definida -- e o padrao usado por
# Railway, Render, Heroku e a maioria dos PaaS modernos (uma unica
# variavel em vez de host/porta/usuario/senha separados). Se nao
# estiver definida, cai de volta nas variaveis DB_* de sempre -- assim
# o desenvolvimento local continua identico, e a escolha do provedor de
# nuvem (ainda pendente) nao exige mudar este arquivo.
if os.getenv('DATABASE_URL'):
    import dj_database_url

    DATABASES = {
        'default': dj_database_url.config(
            env='DATABASE_URL', conn_max_age=600, ssl_require=not DEBUG
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.postgresql'),
            'NAME': os.getenv('DB_NAME', 'sistema_rad'),
            'USER': os.getenv('DB_USER', 'rad_dev'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
#
# 30/07/2026: estes validators sao usados so pelo /admin/ do Django
# (superuser criado via createsuperuser). O login de usuario final do
# Sistema RAD usa validacao propria (usuarios/validadores_senha.py),
# porque o model Usuario nao implementa a interface do
# django.contrib.auth.User que alguns destes validators esperam.

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# STORAGES define dois motores separados: 'default' (anexos de RAD --
# fotos/PDF, ver bloco R2 acima) e 'staticfiles' (CSS/JS do proprio
# sistema, sempre local + WhiteNoise, nunca precisou ir pra nuvem).
#
# Em desenvolvimento (DEBUG=True) nenhum dos dois blocos abaixo roda --
# Django usa os padroes de sempre (disco local pra tudo, runserver
# serve estatico nativamente). So em producao (DEBUG=False) e' que
# isso passa a valer, e mesmo assim 'default' so vira R2 se as
# variaveis R2_* estiverem configuradas -- do contrario continua no
# disco local do Render (com o problema de efemeridade ja conhecido).
if not DEBUG:
    STORAGES = {
        'default': (
            {'BACKEND': 'storages.backends.s3.S3Storage'}
            if USANDO_ARMAZENAMENTO_EM_NUVEM
            else {'BACKEND': 'django.core.files.storage.FileSystemStorage'}
        ),
        'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'},
    }
