# Generated by Django 6.0.7 on 2026-07-15 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rad',
            fields=[
                ('id_rad', models.AutoField(primary_key=True, serialize=False)),
                ('numero_rad', models.CharField(help_text='ID visivel. Formato R00001. Gerado na sincronizacao.', max_length=10, unique=True)),
                ('numero_sa', models.IntegerField(help_text='SA informada pelo usuario. Pode se repetir.')),
                ('numero_execucao', models.IntegerField(help_text='Ordem de execucao dentro da mesma SA. Gerado atomicamente (RG-IDENT-008/009).')),
                ('data_preenchimento', models.DateField()),
                ('km_poste', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_falha', models.IntegerField(blank=True, help_text='Obrigatorio quando tipo_manutencao = Falha.', null=True)),
                ('hora_prog_inicio', models.TimeField()),
                ('data_hp_inicio', models.DateField()),
                ('hora_prog_termino', models.TimeField()),
                ('data_hp_termino', models.DateField()),
                ('hora_real_inicio', models.TimeField()),
                ('data_hr_inicio', models.DateField()),
                ('hora_real_termino', models.TimeField()),
                ('data_hr_termino', models.DateField()),
                ('data_hora_prog_inicio', models.DateTimeField()),
                ('data_hora_prog_termino', models.DateTimeField()),
                ('data_hora_real_inicio', models.DateTimeField()),
                ('data_hora_real_termino', models.DateTimeField()),
                ('duracao_programada_min', models.IntegerField()),
                ('duracao_real_min', models.IntegerField()),
                ('atraso_inicio', models.BooleanField(default=False)),
                ('desc_motivo_atraso_inicio', models.TextField(blank=True, null=True)),
                ('atraso_termino', models.BooleanField(default=False)),
                ('desc_motivo_atraso_termino', models.TextField(blank=True, null=True)),
                ('outros_servico_desc', models.CharField(blank=True, max_length=500, null=True)),
                ('materiais_utilizados', models.TextField(blank=True, null=True)),
                ('observacoes_gerais', models.TextField(blank=True, null=True)),
                ('exportado', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('sincronizado', 'Sincronizado'), ('cancelado', 'Cancelado')], default='sincronizado', max_length=20)),
                ('data_sincronizacao', models.DateTimeField()),
                ('sync_id_tentativa', models.CharField(help_text='ID unico de tentativa. Garante idempotencia em reenvios.', max_length=100, unique=True)),
                ('justificativa_cancelamento', models.TextField(blank=True, null=True)),
                ('data_cancelamento', models.DateTimeField(blank=True, null=True)),
                ('local_final', models.ForeignKey(db_column='id_local_final', on_delete=django.db.models.deletion.PROTECT, related_name='rads_local_final', to='catalogos.catlocal')),
                ('local_inicial', models.ForeignKey(db_column='id_local_inicial', on_delete=django.db.models.deletion.PROTECT, related_name='rads_local_inicial', to='catalogos.catlocal')),
                ('motivo_atraso_inicio', models.ForeignKey(blank=True, db_column='id_motivo_atraso_inicio', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rads_atraso_inicio', to='catalogos.catmotivoatraso')),
                ('motivo_atraso_termino', models.ForeignKey(blank=True, db_column='id_motivo_atraso_termino', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rads_atraso_termino', to='catalogos.catmotivoatraso')),
                ('tipo_manutencao', models.ForeignKey(db_column='id_tipo_manutencao', on_delete=django.db.models.deletion.PROTECT, to='catalogos.cattipomanutencao')),
                ('usuario', models.ForeignKey(db_column='login_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='rads_criados', to='usuarios.usuario', to_field='login')),
                ('usuario_cancelamento', models.ForeignKey(blank=True, db_column='login_cancelamento', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rads_cancelados', to='usuarios.usuario', to_field='login')),
            ],
            options={
                'verbose_name': 'RAD',
                'verbose_name_plural': 'RADs',
                'db_table': 'rad',
            },
        ),
        migrations.CreateModel(
            name='RadAmv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo_mch', models.CharField(max_length=100)),
                ('via_mch', models.CharField(max_length=20)),
                ('ur_mch', models.CharField(max_length=50)),
                ('local_mch', models.CharField(max_length=100)),
                ('linha_mch', models.CharField(max_length=10)),
                ('mch', models.ForeignKey(db_column='id_mch', on_delete=django.db.models.deletion.PROTECT, to='catalogos.catmch')),
                ('rad', models.OneToOneField(db_column='id_rad', on_delete=django.db.models.deletion.CASCADE, related_name='amv', to='rad.rad')),
            ],
            options={
                'verbose_name': 'Bloco AMV',
                'verbose_name_plural': 'Blocos AMV',
                'db_table': 'rad_amv',
            },
        ),
        migrations.CreateModel(
            name='RadAmvAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.ForeignKey(db_column='id_acao', on_delete=django.db.models.deletion.PROTECT, to='catalogos.catacaoamv')),
                ('rad', models.ForeignKey(db_column='id_rad', on_delete=django.db.models.deletion.CASCADE, related_name='amv_acoes', to='rad.rad')),
            ],
            options={
                'verbose_name': 'Acao AMV do RAD',
                'verbose_name_plural': 'Acoes AMV do RAD',
                'db_table': 'rad_amv_acoes',
            },
        ),
        migrations.CreateModel(
            name='RadAmvDefeito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rad', models.ForeignKey(db_column='id_rad', on_delete=django.db.models.deletion.CASCADE, related_name='amv_defeitos', to='rad.rad')),
                ('tipo_defeito', models.ForeignKey(db_column='id_tipo_defeito', on_delete=django.db.models.deletion.PROTECT, to='catalogos.cattipodefeitoamv')),
            ],
            options={
                'verbose_name': 'Defeito AMV do RAD',
                'verbose_name_plural': 'Defeitos AMV do RAD',
                'db_table': 'rad_amv_defeitos',
            },
        ),
        migrations.CreateModel(
            name='RadAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_arquivo', models.CharField(choices=[('foto', 'Foto'), ('pdf', 'PDF')], max_length=10)),
                ('nome_original', models.CharField(max_length=255)),
                ('caminho_servidor', models.CharField(max_length=500)),
                ('tamanho_bytes', models.IntegerField()),
                ('data_upload', models.DateTimeField()),
                ('rad', models.ForeignKey(db_column='id_rad', on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='rad.rad')),
            ],
            options={
                'verbose_name': 'Anexo do RAD',
                'verbose_name_plural': 'Anexos do RAD',
                'db_table': 'rad_anexos',
            },
        ),
        migrations.CreateModel(
            name='RadColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_empresa', models.CharField(blank=True, help_text='Matricula. NULL para participantes externos.', max_length=10, null=True)),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('colaborador', 'Colaborador'), ('participante', 'Participante')], max_length=20)),
                ('rad', models.ForeignKey(db_column='id_rad', on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='rad.rad')),
            ],
            options={
                'verbose_name': 'Colaborador do RAD',
                'verbose_name_plural': 'Colaboradores do RAD',
                'db_table': 'rad_colaboradores',
            },
        ),
        migrations.CreateModel(
            name='RadLinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linha', models.ForeignKey(db_column='codigo_linha', on_delete=django.db.models.deletion.PROTECT, to='catalogos.catlinha')),
                ('rad', models.ForeignKey(db_column='id_rad', on_delete=django.db.models.deletion.CASCADE, related_name='linhas', to='rad.rad')),
            ],
            options={
                'verbose_name': 'Linha do RAD',
                'verbose_name_plural': 'Linhas do RAD',
                'db_table': 'rad_linhas',
            },
        ),
        migrations.CreateModel(
            name='RadServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rad', models.ForeignKey(db_column='id_rad', on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='rad.rad')),
                ('servico', models.ForeignKey(db_column='id_servico', on_delete=django.db.models.deletion.PROTECT, to='catalogos.catservico')),
            ],
            options={
                'verbose_name': 'Servico do RAD',
                'verbose_name_plural': 'Servicos do RAD',
                'db_table': 'rad_servicos',
            },
        ),
        migrations.CreateModel(
            name='RadVia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rad', models.ForeignKey(db_column='id_rad', on_delete=django.db.models.deletion.CASCADE, related_name='vias', to='rad.rad')),
                ('via', models.ForeignKey(db_column='id_via', on_delete=django.db.models.deletion.PROTECT, to='catalogos.catvia')),
            ],
            options={
                'verbose_name': 'Via do RAD',
                'verbose_name_plural': 'Vias do RAD',
                'db_table': 'rad_vias',
            },
        ),
        migrations.AddIndex(
            model_name='rad',
            index=models.Index(fields=['numero_sa'], name='idx_rad_numero_sa'),
        ),
        migrations.AddIndex(
            model_name='rad',
            index=models.Index(fields=['status'], name='idx_rad_status'),
        ),
        migrations.AddIndex(
            model_name='rad',
            index=models.Index(fields=['data_preenchimento'], name='idx_rad_data_preenchimento'),
        ),
        migrations.AddIndex(
            model_name='rad',
            index=models.Index(fields=['usuario'], name='idx_rad_login_usuario'),
        ),
        migrations.AddConstraint(
            model_name='radamvacao',
            constraint=models.UniqueConstraint(fields=('rad', 'acao'), name='uniq_rad_amv_acao'),
        ),
        migrations.AddConstraint(
            model_name='radamvdefeito',
            constraint=models.UniqueConstraint(fields=('rad', 'tipo_defeito'), name='uniq_rad_amv_defeito'),
        ),
        migrations.AddConstraint(
            model_name='radcolaborador',
            constraint=models.UniqueConstraint(condition=models.Q(('registro_empresa__isnull', False)), fields=('rad', 'registro_empresa'), name='uniq_rad_colaborador_registro'),
        ),
        migrations.AddConstraint(
            model_name='radlinha',
            constraint=models.UniqueConstraint(fields=('rad', 'linha'), name='uniq_rad_linha'),
        ),
        migrations.AddConstraint(
            model_name='radservico',
            constraint=models.UniqueConstraint(fields=('rad', 'servico'), name='uniq_rad_servico'),
        ),
        migrations.AddConstraint(
            model_name='radvia',
            constraint=models.UniqueConstraint(fields=('rad', 'via'), name='uniq_rad_via'),
        ),
    ]
