# Generated by Django 6.0.7 on 2026-07-15 11:57

from django.db import migrations

# Sequencia dedicada para o Numero do RAD (EFD-004, formato R00001).
# Usar uma sequence nativa do Postgres garante geracao atomica sem
# necessidade de lock manual (nextval() e thread-safe por design).
# Nomenclatura conforme PADROES_E_DIRETRIZES 4.2: seq_[tabela].


class Migration(migrations.Migration):

    dependencies = [
        ('rad', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE SEQUENCE IF NOT EXISTS seq_numero_rad START WITH 1;",
            reverse_sql="DROP SEQUENCE IF EXISTS seq_numero_rad;",
        ),
    ]
