# Generated by Django 6.0.7 on 2026-07-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rad', '0002_seq_numero_rad'),
    ]

    operations = [
        migrations.AddField(
            model_name='radanexo',
            name='categoria_foto',
            field=models.CharField(blank=True, choices=[('intervencao_verificada', 'Intervenção verificada'), ('acao_realizada', 'Ação realizada')], help_text='Obrigatorio quando tipo_arquivo=foto. Nulo para PDF.', max_length=30, null=True),
        ),
        migrations.AddConstraint(
            model_name='radanexo',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('categoria_foto__isnull', False), ('tipo_arquivo', 'foto')), models.Q(('categoria_foto__isnull', True), ('tipo_arquivo', 'pdf')), _connector='OR'), name='chk_rad_anexo_categoria_coerente_com_tipo'),
        ),
    ]
