# Generated by Django 6.0.7 on 2026-07-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
        ('rad', '0004_rename_sa_to_os_and_add_numero_sa'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rad',
            name='idx_rad_numero_os',
        ),
        migrations.AlterField(
            model_name='rad',
            name='numero_execucao',
            field=models.IntegerField(help_text='Ordem de execucao dentro da mesma OS. Gerado atomicamente (RG-IDENT-008/009).'),
        ),
        migrations.AddIndex(
            model_name='rad',
            index=models.Index(fields=['numero_os'], name='idx_rad_numero_os'),
        ),
    ]
