# Generated by Django 6.0.7 on 2026-07-17 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_catequipe'),
        ('rad', '0005_remove_rad_idx_rad_numero_os_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rad',
            name='descricao_tecnica_atividade',
            field=models.TextField(blank=True, help_text='Sem limite de caracteres. Aceita qualquer caractere.', null=True),
        ),
        migrations.AddField(
            model_name='rad',
            name='operador_ccm',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='rad',
            name='responsavel_atividade',
            field=models.CharField(blank=True, help_text='Obrigatorio quando o campo estiver habilitado (VLD-029).', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='RadEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe', models.ForeignKey(db_column='codigo_equipe', on_delete=django.db.models.deletion.PROTECT, to='catalogos.catequipe')),
                ('rad', models.ForeignKey(db_column='id_rad', on_delete=django.db.models.deletion.CASCADE, related_name='equipes', to='rad.rad')),
            ],
            options={
                'verbose_name': 'Equipe do RAD',
                'verbose_name_plural': 'Equipes do RAD',
                'db_table': 'rad_equipes',
                'constraints': [models.UniqueConstraint(fields=('rad', 'equipe'), name='uniq_rad_equipe')],
            },
        ),
    ]
