# Generated by Django 6.0.7 on 2026-08-14 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rad', '0014_multiplos_blocos_amv'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadCanaleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grau_criticidade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], max_length=10)),
                ('necessita_cautela', models.BooleanField()),
                ('largura_inicial', models.DecimalField(decimal_places=2, max_digits=8)),
                ('largura_final', models.DecimalField(decimal_places=2, max_digits=8)),
                ('altura_inicial', models.DecimalField(decimal_places=2, max_digits=8)),
                ('altura_final', models.DecimalField(decimal_places=2, max_digits=8)),
                ('comprimento', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rad', models.OneToOneField(db_column='id_rad', on_delete=django.db.models.deletion.CASCADE, related_name='canaleta', to='rad.rad')),
            ],
            options={
                'verbose_name': 'Bloco Anomalias (Canaleta)',
                'verbose_name_plural': 'Blocos Anomalias (Canaleta)',
                'db_table': 'rad_canaleta',
            },
        ),
        migrations.CreateModel(
            name='RadCanaletaAnomalia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomalia', models.CharField(choices=[('limpa', 'Limpa'), ('obstruida', 'Obstruída'), ('ausente', 'Ausente'), ('quebrada', 'Quebrada'), ('vegetacao', 'Vegetação'), ('lastro', 'Lastro'), ('lixo', 'Lixo'), ('dormentes', 'Dormentes'), ('entulho', 'Entulho'), ('terra', 'Terra')], max_length=20)),
                ('canaleta', models.ForeignKey(db_column='id_canaleta', on_delete=django.db.models.deletion.CASCADE, related_name='anomalias', to='rad.radcanaleta')),
            ],
            options={
                'verbose_name': 'Anomalia da Canaleta',
                'verbose_name_plural': 'Anomalias da Canaleta',
                'db_table': 'rad_canaleta_anomalias',
                'constraints': [models.UniqueConstraint(fields=('canaleta', 'anomalia'), name='uniq_canaleta_anomalia')],
            },
        ),
        migrations.CreateModel(
            name='RadCanaletaLado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lado', models.CharField(choices=[('direito', 'Direito'), ('esquerdo', 'Esquerdo'), ('entrevia', 'Entrevia')], max_length=10)),
                ('canaleta', models.ForeignKey(db_column='id_canaleta', on_delete=django.db.models.deletion.CASCADE, related_name='lados', to='rad.radcanaleta')),
            ],
            options={
                'verbose_name': 'Lado da Canaleta',
                'verbose_name_plural': 'Lados da Canaleta',
                'db_table': 'rad_canaleta_lados',
                'constraints': [models.UniqueConstraint(fields=('canaleta', 'lado'), name='uniq_canaleta_lado')],
            },
        ),
    ]
