# Generated by Django 6.0.7 on 2026-08-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rad', '0018_data_ultima_exportacao_excel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radcanaleta',
            name='justificativa',
            field=models.TextField(blank=True, help_text='Obrigatoria (VLD-045) quando grau_criticidade e Media, Alta ou Critica. Sem limite de caracteres.', null=True),
        ),
    ]
