# Generated by Django 6.0.7 on 2026-09-04 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0012_inspecao_canaleta'),
        ('rad', '0019_alter_radcanaleta_justificativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='radamv',
            name='desc_mch_nao_cadastrada',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='radamv',
            name='mch_nao_cadastrada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='radamv',
            name='linha_mch',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='radamv',
            name='local_mch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='radamv',
            name='mch',
            field=models.ForeignKey(blank=True, db_column='id_mch', null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.catmch'),
        ),
        migrations.AlterField(
            model_name='radamv',
            name='modelo_mch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='radamv',
            name='ur_mch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='radamv',
            name='via_mch',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='radamv',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('mch__isnull', False), ('mch_nao_cadastrada', False)), models.Q(('mch__isnull', True), ('mch_nao_cadastrada', True)), _connector='OR'), name='chk_rad_amv_mch_xor_nao_cadastrada'),
        ),
    ]
