# Generated by Django 6.0.7 on 2026-09-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rad', '0020_radamv_desc_mch_nao_cadastrada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rad',
            name='data_atividade',
            field=models.DateField(blank=True, null=True),
        ),
    ]
