# Generated by Django 6.0.7 on 2026-09-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rad', '0021_rad_data_atividade'),
    ]

    operations = [
        migrations.AddField(
            model_name='rad',
            name='km_poste_final',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rad',
            name='km_poste_inicial',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
