# Generated by Django 6.0.7 on 2026-09-17 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rad', '0022_rad_km_poste_final_rad_km_poste_inicial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='radcanaleta',
            options={'ordering': ['id'], 'verbose_name': 'Anomalia Observada', 'verbose_name_plural': 'Anomalias Observadas'},
        ),
        migrations.AddField(
            model_name='rad',
            name='data_ultimo_envio_drive',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='radcanaleta',
            name='altura_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='radcanaleta',
            name='altura_inicial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='radcanaleta',
            name='comprimento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='radcanaleta',
            name='km_poste_final',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='radcanaleta',
            name='km_poste_inicial',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='radcanaleta',
            name='largura_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='radcanaleta',
            name='largura_inicial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='radcanaleta',
            name='justificativa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='radcanaleta',
            name='rad',
            field=models.ForeignKey(db_column='id_rad', on_delete=django.db.models.deletion.CASCADE, related_name='canaleta_itens', to='rad.rad'),
        ),
    ]
