# Generated by Django 6.0.7 on 2026-09-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rad', '0023_alter_radcanaleta_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radcanaletaanomalia',
            name='anomalia',
            field=models.CharField(choices=[('limpa', 'Limpa'), ('obstruida', 'Obstruída'), ('ausente', 'Ausente'), ('quebrada', 'Quebrada'), ('vegetacao', 'Vegetação'), ('lastro', 'Lastro'), ('lixo', 'Lixo'), ('dormentes', 'Dormentes'), ('entulho', 'Entulho'), ('terra', 'Terra'), ('esgoto', 'Esgoto')], max_length=20),
        ),
    ]
