# Generated by Django 6.0.7 on 2026-09-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rad', '0024_alter_radcanaletaanomalia_anomalia'),
    ]

    operations = [
        migrations.AddField(
            model_name='rad',
            name='data_ultima_sincronizacao_planilha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
