# Generated by Django 6.0.7 on 2026-09-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rad', '0025_rad_data_ultima_sincronizacao_planilha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rad',
            name='numero_os',
            field=models.BigIntegerField(help_text='OS informada pelo usuario. Pode se repetir.'),
        ),
    ]
